server:
  port: 8080
  tomcat:
    max-http-form-post-size:
  servlet:
    context-path: /board

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?characterEncoding=utf-8
    username: root
    password: 123456

  thymeleaf:
    prefix: classpath:/templates/

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
